Добавлена страница компонента с-layout
js-tasks-ru/htmlcss-20220919_grebady pull request #16
Opened 2023-01-16 18:44 UTC by Grebady

2023-01-16 18:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-01-27 19:57 UTC, GSemikozov requested changes

2023-01-27 19:57 UTC, GSemikozov commented on components/c-layout/c-layout.css
> +html, body {
глобальные стили - не стили компонента

2023-02-05 11:54 UTC, Grebady commented on components/c-layout/c-layout.css
> +html, body {
Кажется, здесь вообще эти строки лишние. Убрал их и всё продолжает работать

2023-02-06 10:08 UTC, GSemikozov requested changes

2023-02-06 10:08 UTC, GSemikozov commented on components/c-sidebar/c-sidebar.css
> +.c-sidebar__link_link {
link с модификатором link?) видимо лишнее, либо надо поменять названия классов

2023-02-06 10:08 UTC, GSemikozov commented on components/c-sidebar/c-sidebar.css
> +    grid-area: sidebar;
сам компонент ничего не знает заранее о своем контексте использования, так что области надо задавать через элементы того блока в который мы будем встраивать данный

2023-02-06 10:08 UTC, GSemikozov commented on components/c-main/c-main.css
> +    grid-area: main;
см коммент ниже

2023-02-06 18:01 UTC, closed without merging