Сделано дз с кнопками
js-tasks-ru/htmlcss-20220919_grebady pull request #3
Opened 2022-09-28 12:56 UTC by Grebady

2022-09-28 12:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 21:15 UTC, GSemikozov requested changes

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 11.375rem;
лишнее ограничение ширины (ширина должна зависеть от внутреннего содержимого)

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 11.375rem;
и тогда не хватает паддингов

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.c-button-primary-default {
модификатор пишется через 1 нижнее подчеркивание .c-button_primary

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.c-button-primary-default {
надо поправить везде ниже

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.c-button-primary-disabled {
модификатор здесь не нужен, есть встроенный псевдокласс для данного состояния, поэтому - .c-button_primary:disabled. Но и здесь небольшая поправка - disabled общий для всех типов кнопок, поэтому - .button:disabled

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background: #2342C0;
цвета менять не надо, достаточно полупрозрачности

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2022-09-28 21:15 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +          <button class="c-button c-button-primary-disabled">Primary</button>
`<button class="c-button c-button_primary" disabled>Primary</button>`

2022-09-29 09:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 12:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 20:12 UTC, GSemikozov approved these changes

2022-09-29 20:12 UTC, merged